import { test, expect } from "@playwright/test";
test('Edit Lead', async ({ page }) => {

    await page.goto("http://leaftaps.com/opentaps/control/main")
    await page.locator('#username').fill('demoCSR2')
    await page.locator('#password').fill('crmsfa')
    await page.locator('.decorativeSubmit').click()
    await page.locator('.crmsfa').click()
    await page.waitForTimeout(6000)
    await page.locator('//a[text()="Leads"]').click()
    await page.waitForTimeout(6000)
    await page.locator('//a[text()="Create Lead"]').click()
    await page.locator('#createLeadForm_companyName').fill('Yectra1')
    await page.locator('#createLeadForm_firstName').fill('Nithya1')
    await page.locator('#createLeadForm_lastName').fill('Marimuthu1')
    await page.locator('.smallSubmit').click()
    await page.waitForTimeout(6000)
    await page.locator('//a[text()="Edit"]').click()
    await page.locator('#updateLeadForm_companyName').fill('Yectra2')
    await page.locator('//input[@value="Update"]').click()
    await page.waitForTimeout(6000)
    //await expect(page.locator('#viewLead_generalProfTitle_sp')).toHaveText('Nithya1')
    //await expect(page.locator('#viewLead_generalProfTitle_sp')).toContainText(/Yectra2/)
})